# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gara.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicle_name', models.CharField(max_length=256)),
                ('seria_number', models.CharField(max_length=256)),
                ('year', models.DateTimeField()),
                ('model', models.CharField(max_length=256, validators=[gara.validators.validate_category])),
                ('cost', models.FloatField(max_length=100)),
                ('amount_sale', models.FloatField(max_length=100)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256, validators=[gara.validators.validate_name])),
                ('customer_adddress', models.CharField(max_length=256)),
                ('customer_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_tradein', models.BooleanField()),
                ('price_sold', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='gara.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=256)),
                ('quanity', models.FloatField()),
                ('amount_sale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_name', models.CharField(max_length=256, validators=[gara.validators.validate_name])),
                ('salesman_adddress', models.CharField(max_length=256)),
                ('salesman_phone', models.CharField(max_length=256, validators=[gara.validators.validate_phone])),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=256)),
                ('seria_number', models.CharField(max_length=256)),
                ('year', models.DateField()),
                ('model', models.CharField(max_length=256)),
                ('cost', models.FloatField(validators=[gara.validators.validate_number])),
                ('amount_sale', models.FloatField(validators=[gara.validators.validate_number])),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdraw')], max_length=1)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manufacturer', to='gara.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_id',
            field=models.ManyToManyField(to='gara.Option'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Salesman', to='gara.Salesman'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='gara.Vehicle'),
        ),
    ]
